### ISSUE TITLE
webkit多行省略号

### ISSUE THREAD

**Issue by luohong123** [luohong123/daydayup#12]
```css
div{
  overflow : hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
```
